#!/usr/bin/env bash
#Script that Install and configure HAproxy on your lb-01 server.
#Configures HAproxy so that it send traffic to web-01 and web-02.
#Distributes requests using a roundrobin algorithm.
#HAproxy can be managed via an init script.
#hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.

sudo apt-get update
sudo apt-get -y inshall haproxy
cat << EOF |sudo tee -a /etc/haproxy/haproxy.cfg
listen load_balancer
        bind :80
	mode http
	option httpclose
	option forwardfor
        balance roundrobin
        server 158811-web-01 100.25.150.78:80 check
        server 158811-web-02 3.84.255.243:80 check
EOF
sudo service haproxy restart
